# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'VKApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VKApp
pod 'RealmSwift', '~>10'
pod 'Kingfisher', '~> 7.0'
pod 'Alamofire', '~> 5.4'

end
